name: Automated Code Scan

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize
        uses: github/codeql-action/init@v1

      - name: Build
        uses: github/codeql-action/autobuild@v1

      - name: Analyze
        uses: github/codeql-action/analyze@v1