name: Automated Linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analyze
      run: |
        pylint `ls -R|grep .py$|xargs`
